#!/bin/sh
sed -i -e 's/unsigned long/ULONG/g' asio.h
sed -i -e 's/long long int/LONGLONG/g' asio.h
sed -i -e 's/long int/LONG/g' asio.h
sed -i -e 's/long/LONG/g' asio.h
sed -i -e 's/(\*bufferSwitch)/(CALLBACK *bufferSwitch)/g' asio.h
sed -i -e 's/(\*sampleRateDidChange)/(CALLBACK *sampleRateDidChange)/g' asio.h
sed -i -e 's/(\*asioMessage)/(CALLBACK *asioMessage)/g' asio.h
sed -i -e 's/(\*bufferSwitchTimeInfo)/(CALLBACK *bufferSwitchTimeInfo)/g' asio.h
